### PR TITLE
Refactor and refocus the lesson

### PR DESCRIPTION
**Pull request by bast**
This is a massive work in progress pull request and I understand that it is not easy to follow changes by looking at the diffs and it is probably easier to look at the result: https://coderefinery.github.io/reproducible-research-aalborg/

This work is not finished yet, I plan to still rework the episode "Recording computational steps" where I want to present and discuss a comparison GUI vs manual steps vs script vs Snakemake vs Make.

### CODE REVIEW

**Comment by bast** [comment]
Motivation for the rewrite:
- goal is not that participants are able to write a Snakefile (that would be a valid goal but is not my personal goal)
- my goal is that participants see which of the many tools are a good fit for what they do, later they can figure out details on their own
- hopefully more discussion
- hopefully some must-haves will be more visible

**Comment by bast** [comment]
TODO: Somehow I removed the Conda exercise but my plan was to leave it as optional episode. I need to reinsert that.

**Comment by bast** [comment]
Left to do:
- [ ] reintroduce conda exercise
- [ ] rename link from word-count-aalborg to word-count

**Comment by bast** [comment]
[chat:]
> i also think there should be an exercise on conda, e.g. creating an environment, installing particular versions and exporting an environments file

These steps are described in the episode. We can spin this into an exercise but I would welcome if we can follow-up on this with an issue.

**Comment by bast** [comment]
Once merged, please remove https://github.com/coderefinery/reproducible-research-aalborg and rename link in 2019-06-11-aalborg.md.

**Comment by rkdarst** [comment]
This revision makes me very happy.

These should be made another issue:
- [ ] There could be a exercise on adding requirements.txt or some such to a project.  It can also be used to detect hidden dependencies (e.g. exercise has a few things declared in the README, but a hidden function imports something else)
- [ ] Mention that making pip/conda environments is also useful because it helps you make sure that *you* know your dependencies (relates to above).

**Comment by wikfeldt** [comment]
great to have better organization of the episodes! so i approve this PR.
here are some things that i think should be improved:
- more hands-on exercises. If it's not snakemake or make we should try to come up with more concrete exercises. Discussions are good but participants almost unanimously want more hands-on
- would be good to consistently use "task" sections for exercises, since it makes it easier to browse the episodes
- currently too python-centric, questions is how to improve it. Either we 
   - include more tools, perhaps GUIX/NIX, something from R world, etc, 
   - or we reduce text on pyenv, poetry, virtualenv etc and perhaps instead show examples of conda for different languages.

**Comment by bast** [comment]
Thanks for very good comments. OK if I spawn new issues based on the suggestions and merge?

**Comment by bast** [comment]
> more hands-on exercises. If it's not snakemake or make we should try to come up with more concrete exercises. Discussions are good but participants almost unanimously want more hands-on

I agree generally but I also think that at 4:30 pm after a long day, in my opinion a longer hands-on exercise is often not what participants want. But we should have more hands-on as optional episodes, also for the case where this lesson is used earlier in the day.

Also the discussion section can involve hands-on. Depending on time of day and mood in the room, I would encourage participants to actually try the scripted, snakemake, and make examples and experience the pros and cons.

**Comment by wikfeldt** [comment]
yeah sure, i left it open in case you wanted input from others as well, but ready to merge from my perspective

**Comment by bast** [comment]
> yeah sure, i left it open in case you wanted input from others as well, but ready to merge from my perspective

OK I will create issues, merge, and also clean up the URL references in the workshop page.

**Comment by bast** [comment]
Issues created, URLs are fixed. Merging.

**Pull request merged**
