### PR TITLE
Thor snakemake

### PR DESCRIPTION
**Pull request by wikfeldt**
i've replaced the example project with a similar but more extended example, for which there's also a snakefile. The idea is to compare make with snakemake, and run both inside docker container. The container episode is yet to be updated and the snakemake episode is missing

### CODE REVIEW

**Comment by bast** [comment]
Ah - WIP, not merging yet, should not have used the approving :-)

**Comment by bast** [comment]
I like the example.

**Comment by bast** [comment]
I think we went overtime with this lesson last time and now more stuff got added. It is possible to deliver it but also consider removing content or at least prepare to jump over optionals which I trust you do - just a note.

**Comment by wikfeldt** [comment]
yes i'm aware of the time constraint. it looks like a lot of material but much of it will be for later study. the dilemma is to include enough to demonstrate the usefulness of a tool while not hurrying through it too fast

**Comment by wikfeldt** [comment]
aha didn't realize that. 
follow-up question then, in the docker container i install python3 (in ubuntu 16.04), but no `python` symlink is created. This means that "python program.py" won't work.
Should this be done manually in the dockerfile or is there a basic python-installation way to do it that i don't know about?

**Comment by bast** [comment]
Sorry I don't know enough about Docker files or Ubuntu to answer that.

**Comment by wikfeldt** [comment]
i've replaced ./foo.py with python foo.py and removed shebangs from source files in example project (which is now at https://github.com/coderefinery/word-count).
Ready to merge i think

**Pull request merged**
