### PR TITLE
Links, Intro and where to go from here

### LINKED ISSUE #239: Full lesson summary
I am missing here a full lesson summary that brings everything together and talks a bit about when which of the tools are useful, and when not.

### LINKED ISSUE #241: Adapt to new timeframe
2 hours in beginning of day 4. This is the beginning of week 2, so the beginning of the lesson could be used to put everything already done and everything coming up into perspective. 

Include break and minimum 10 min for each exercise, consider demos, where applicable; think researcher.

### LINKED ISSUE #243: Link to https://epcced.github.io/2023-09-06-rse-singularity/
Good lesson material about Singularity/Apptainer.

### LINKED ISSUE #254: Motivation pyramid image citation
Is this the correct "origin" for the pyramid image in the Motivation part: https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/fig/01-fig5.png ?
Or did someone from CodeRefinery create the figure

In our materials it is marked as [citation needed]

### PR DESCRIPTION
**Pull request by samumantha**
* add carpentries incubator links to container lessons, closes #243 
* add R book link #235 
* move Heidis illustration to new intro page to connect all CodeRefinery lessons and explain a bit why the lessons are what they are and how they connect , closes #241
* Add where to go from here section, discussing when the tools discussed in this lesson may be useful (draft! please comment)
* add short section on different needs to container episode, closes #239 and maybe #237 ?
* add pyramid citation, closes #254

### CODE REVIEW

**Comment by samumantha** [comment]
Also linking this here for reference (Enrico and Samantha planning doc for Sep 23 workshop): https://hackmd.io/@coderefinery/HyG-lYb1p

**Review by bast — APPROVED** [review]
I really like the "how it all connects" approach. This is a big improvement.

**Comment by samumantha** [comment]
Let's not merge this yet, though but use this for discussion around the materials, all suggestions welcome.

**Comment by samumantha** [comment]
If you have a moment @bast and @eglerean (or also others :) ) :
Please take a look at `where-to-go.md`; the idea was to add a new section to the end of the lesson and bringing it into more practical focus, or answering "do I really need (to know) all of this?". 
Very happy to discuss better formulations or ways to present this, currently out of ideas...

**Comment by samumantha** [comment]
Continuing work tomorrow on the "how it all connects part". Images are there, but I still want to connect them; which will probably be Heidis slide and then handrwritten lesson titles connected to the point where they connect to.
Also happy to hear if you have any comments about that before I start

**Comment by samumantha** [comment]
How about this? -> reproducible_research_plus_lessons.png

**Comment by bast** [comment]
I read through the changes. It is clearly better than before and I would merge and spawn smaller PRs based on this once it is in?

**Comment by samumantha** [comment]
Oke, if you think so 😉

**Pull request merged**
