### PR TITLE
Moved "sharing" to social coding and reordered according to schedule 

### PR DESCRIPTION
**Pull request by samumantha**
* Sharing removed from here, now in https://github.com/coderefinery/social-coding/pull/138
* some typos fixed
* reordered lessons according to schedule for sep workshop

Please merge asap if all is ok...more to come in next days :)

### CODE REVIEW

**Review by bast — APPROVED** [review]
Approved but let us take a record of the authors who are about to be lost if we flatten history of the moved files to other repo (maybe best to add them there to citation.cff draft).

**Comment by bast** [comment]
Maybe to clarify my cryptic comment: I want to make sure that all people who contributed to the deleted episode get added as author to the other repo.

**Comment by samumantha** [comment]
Very good point! 
So, do we leave everyone in this lessons author list or do we remove people that have only contributed to the sharing lesson and add them to social coding?

**Comment by bast** [comment]
We don't need to remove. It's important for me that they are added on the other side.

**Comment by samumantha** [comment]
ok can do that in ~30 min :+1:

**Pull request merged**
