### PR TITLE
mixed updates

### PR DESCRIPTION
**Pull request by wikfeldt**
depends on #120

### CODE REVIEW

**Comment by bast** [comment]
Conflicts now. Let me know if I should help with the conflict resolution.

**Comment by wikfeldt** [comment]
conflicts resolved. awaiting approval

**Comment by bast** [comment]
I was wondering whether importing or generating from template would be easier to do? But perhaps there is good reason for going for the import?

**Comment by wikfeldt** [comment]
these changes were not meant to change from generating-from-template to importing the word-count example. I added a commit to clarify that learners should use the "Use this template" feature

**Comment by wikfeldt** [comment]
changes approved, so self-merging

**Pull request merged**
